owner = "milkyskies"
repo = "worldsim"
project_number = 15
status_field_id = "PVTSSF_lAHOAGCvbs4BUG4CzhBRRMY"
priority_field_id = "PVTSSF_lAHOAGCvbs4BUG4CzhBRRNc"
points_field_id = "PVTF_lAHOAGCvbs4BUG4CzhBRRNg"
