//! Multi-plan cognitive memory: plans live in explicit states (#338).
//!
//! Reads: PlanMemory (pure data written by brain systems)
//! Writes: PlanMemory (per-tick state transitions, commitment, eviction)
//! Upstream: rational brain (plan generation + promotion), communication (verbal plan insert)
//! Downstream: rational_brain_propose (executing-state plans surface as proposals),
//!             communication (background plans surface as share content)
//!
//! Replaces `RationalBrain.current_plan: Option<Plan>`. Each plan is a
//! `HeldPlan` carrying its own lifecycle state, commitment value, source,
//! and progress cursor. Plans flow Background → Considering → Executing;
//! channel conflicts at execution time push Executing plans back to
//! Suspended; uninteresting background plans get evicted when the
//! agent's working-memory cap is exceeded.

use crate::agent::brains::proposal::BrainType;
use crate::agent::brains::thinking::{ActionTemplate, Goal};
use bevy::prelude::*;

/// Stable identifier for a `HeldPlan` within a single agent's memory.
/// Unique per agent, not globally — two different agents can hold the
/// same id without clashing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Reflect)]
pub struct PlanId(pub u64);

/// Cognitive phase a plan is currently in. Plans migrate between states
/// each thinking cycle as conditions, commitment, and body-channel
/// availability change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Reflect, Default)]
pub enum PlanState {
    /// In the back of the mind. Not executing, slowly accumulating
    /// commitment. May surface during conversation. Doesn't touch body
    /// channels. New plans from non-urgent drives enter here.
    #[default]
    Background,
    /// Foreground deliberation. Commitment accumulates faster (per #329
    /// math) and the plan is queued to promote as soon as it crosses
    /// threshold.
    Considering,
    /// The plan's current step is feeding the action channel system and
    /// running. Multiple Executing plans coexist as long as their steps
    /// don't hard-conflict on any body channel.
    Executing,
    /// Was Executing, got displaced by a higher-priority plan that
    /// needed the same body channels. Held in memory so it can resume
    /// once the conflict clears.
    Suspended,
}

/// Where a plan came from. Drives some personality and priority math and
/// lets the UI distinguish "something I decided" from "something I
/// promised another agent."
#[derive(Debug, Clone, Copy, PartialEq, Eq, Reflect)]
pub enum PlanSource {
    /// Self-generated by one of the agent's own brains.
    Brain(BrainType),
    /// Emerged from a verbal agreement with another agent — absorbed from
    /// the old `Commitments` component (#63 migration target).
    VerbalCommitment {
        promised_to: Entity,
        agreement_tick: u64,
    },
}

impl PlanSource {
    /// Verbal commitments surface higher priority in conversation and
    /// resist eviction more than self-generated plans.
    pub fn is_verbal_commitment(&self) -> bool {
        matches!(self, PlanSource::VerbalCommitment { .. })
    }
}

/// A plan held in an agent's cognitive memory. Combines goal, generated
/// action sequence, lifecycle state, commitment accumulation, and
/// provenance into one value. Each agent holds a `Vec<HeldPlan>` inside
/// their `PlanMemory` component.
#[derive(Debug, Clone, Reflect)]
pub struct HeldPlan {
    pub id: PlanId,
    pub goal: Goal,
    pub steps: Vec<ActionTemplate>,
    pub state: PlanState,
    /// Continuous commitment value (0..∞) accumulated per tick via the
    /// #329 math. Crosses a cost-derived threshold to promote
    /// Background → Considering → Executing.
    pub commitment: f32,
    /// Subjective cost of the full plan, captured at creation time via
    /// `estimate_plan_cost`. Feeds the commit threshold.
    pub subjective_cost: f32,
    /// Source of the plan — own brain vs. verbal commitment.
    pub source: PlanSource,
    /// Tick the plan was generated.
    pub created_at: u64,
    /// Last tick the plan was touched by any system (state change,
    /// commitment accumulation, progress). Drives eviction scoring.
    pub last_touched: u64,
    /// Index into `steps` of the action currently running (Executing) or
    /// paused (Suspended). Ignored for Background/Considering.
    pub current_step: usize,
}

impl HeldPlan {
    /// True when the plan's execution cursor has reached the end of its
    /// step list. The brain's plan-verification pass drops finished
    /// plans from `PlanMemory`.
    pub fn is_finished(&self) -> bool {
        self.current_step >= self.steps.len()
    }

    /// The plan's current step, if execution is still in progress.
    /// Returns `None` when the plan is empty or finished.
    pub fn current(&self) -> Option<&ActionTemplate> {
        self.steps.get(self.current_step)
    }
}

// ─── Cognitive load constants ──────────────────────────────────────────────

/// Baseline cap on total held plans for a neutral-personality agent.
/// Conscientiousness and openness lift this cap; neuroticism lowers it.
pub const BASE_MAX_PLANS: usize = 5;

/// Maximum boost from personality traits. A fully conscientious + open
/// agent holds `BASE + PERSONALITY_CAP_BOOST` plans.
pub const PERSONALITY_CAP_BOOST: usize = 3;

/// Species cap for non-human animals — their plan memory is much
/// shallower than a full cognitive agent's.
pub const ANIMAL_MAX_PLANS: usize = 2;

/// Compute the personality-modulated cap on total plan count for a
/// human-class agent.
pub fn max_plans_for(openness: f32, conscientiousness: f32, neuroticism: f32) -> usize {
    let boost = ((openness + conscientiousness) * 0.5 - neuroticism * 0.5).clamp(0.0, 1.0);
    BASE_MAX_PLANS + (boost * PERSONALITY_CAP_BOOST as f32).round() as usize
}

/// Agent's cognitive working memory of plans.
///
/// Replaces `RationalBrain.current_plan`. Each entry is a full `HeldPlan`
/// with its own lifecycle state. The rational brain reads/writes this
/// component instead of owning a single optional plan.
#[derive(Component, Debug, Clone, Default, Reflect)]
#[reflect(Component)]
pub struct PlanMemory {
    #[reflect(ignore)]
    pub plans: Vec<HeldPlan>,
    /// Monotonic counter used to mint unique `PlanId`s per agent. Never
    /// reused even after a plan is evicted.
    #[reflect(ignore)]
    next_id: u64,
}

impl PlanMemory {
    /// Mint a fresh, never-recycled plan id for this agent's memory.
    pub fn mint_plan_id(&mut self) -> PlanId {
        let id = PlanId(self.next_id);
        self.next_id += 1;
        id
    }

    /// Total number of plans currently held across all states.
    pub fn len(&self) -> usize {
        self.plans.len()
    }

    /// True when no plans are held.
    pub fn is_empty(&self) -> bool {
        self.plans.is_empty()
    }

    /// Count plans in a given state.
    pub fn count_state(&self, state: PlanState) -> usize {
        self.plans.iter().filter(|p| p.state == state).count()
    }

    /// Iterate plans in a given state.
    pub fn in_state(&self, state: PlanState) -> impl Iterator<Item = &HeldPlan> {
        self.plans.iter().filter(move |p| p.state == state)
    }

    /// Mutably iterate plans in a given state.
    pub fn in_state_mut(&mut self, state: PlanState) -> impl Iterator<Item = &mut HeldPlan> {
        self.plans.iter_mut().filter(move |p| p.state == state)
    }

    /// Lookup a plan by id.
    pub fn get(&self, id: PlanId) -> Option<&HeldPlan> {
        self.plans.iter().find(|p| p.id == id)
    }

    /// Mutable lookup by id.
    pub fn get_mut(&mut self, id: PlanId) -> Option<&mut HeldPlan> {
        self.plans.iter_mut().find(|p| p.id == id)
    }

    /// Find an existing plan targeting the given goal. Goals compare by
    /// conditions (not priority) per the `PartialEq` impl on `Goal`.
    pub fn by_goal(&self, goal: &Goal) -> Option<&HeldPlan> {
        self.plans.iter().find(|p| &p.goal == goal)
    }

    /// Mutable lookup by goal.
    pub fn by_goal_mut(&mut self, goal: &Goal) -> Option<&mut HeldPlan> {
        self.plans.iter_mut().find(|p| &p.goal == goal)
    }

    /// Insert a fresh plan and return its id. The caller is responsible
    /// for any pre-existing plan targeting the same goal — use
    /// `replace_for_goal` to atomically replace instead.
    pub fn insert(&mut self, plan: HeldPlan) -> PlanId {
        let id = plan.id;
        self.plans.push(plan);
        id
    }

    /// Remove a plan by id. Returns true if a plan was removed.
    pub fn remove(&mut self, id: PlanId) -> bool {
        let before = self.plans.len();
        self.plans.retain(|p| p.id != id);
        self.plans.len() != before
    }

    /// Remove every plan matching the given goal. Returns the number
    /// removed.
    pub fn remove_by_goal(&mut self, goal: &Goal) -> usize {
        let before = self.plans.len();
        self.plans.retain(|p| &p.goal != goal);
        before - self.plans.len()
    }

    /// Evict Background plans with the lowest commitment until the total
    /// plan count is at or below `max_plans`. Verbal commitments are
    /// protected — eviction prefers self-generated background plans
    /// first, falling back to verbal only when there is nothing else to
    /// drop. Returns the ids of evicted plans.
    pub fn evict_excess(&mut self, max_plans: usize) -> Vec<PlanId> {
        let mut evicted = Vec::new();
        while self.plans.len() > max_plans {
            // Find the weakest Background plan (prefer non-verbal
            // commitments); if no Background plans exist, fall back to
            // Suspended, then Considering. Executing plans are never
            // auto-evicted — the brain must explicitly demote them.
            let victim = Self::pick_eviction_victim(&self.plans);
            match victim {
                Some(idx) => {
                    evicted.push(self.plans[idx].id);
                    self.plans.remove(idx);
                }
                None => break,
            }
        }
        evicted
    }

    fn pick_eviction_victim(plans: &[HeldPlan]) -> Option<usize> {
        // Eviction preference order: Background non-verbal → Background
        // verbal → Suspended → Considering. Within each group pick the
        // lowest commitment.
        let preference = [
            (PlanState::Background, false),
            (PlanState::Background, true),
            (PlanState::Suspended, false),
            (PlanState::Suspended, true),
            (PlanState::Considering, false),
            (PlanState::Considering, true),
        ];
        for (state, verbal) in preference {
            let candidate = plans
                .iter()
                .enumerate()
                .filter(|(_, p)| p.state == state && p.source.is_verbal_commitment() == verbal)
                .min_by(|(_, a), (_, b)| {
                    a.commitment
                        .partial_cmp(&b.commitment)
                        .unwrap_or(std::cmp::Ordering::Equal)
                });
            if let Some((idx, _)) = candidate {
                return Some(idx);
            }
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::brains::thinking::TriplePattern;
    use crate::agent::mind::knowledge::{Concept, Node as MindNode, Predicate, Value};

    fn test_goal(concept: Concept) -> Goal {
        Goal {
            conditions: vec![TriplePattern::new(
                Some(MindNode::Self_),
                Some(Predicate::Contains),
                Some(Value::Item(concept, 1)),
            )],
            priority: 0.5,
        }
    }

    fn held_plan(id: u64, state: PlanState, source: PlanSource, commitment: f32) -> HeldPlan {
        HeldPlan {
            id: PlanId(id),
            goal: test_goal(Concept::Apple),
            steps: Vec::new(),
            state,
            commitment,
            subjective_cost: 0.0,
            source,
            created_at: 0,
            last_touched: 0,
            current_step: 0,
        }
    }

    #[test]
    fn mint_plan_id_is_monotonic_and_unique() {
        let mut mem = PlanMemory::default();
        let a = mem.mint_plan_id();
        let b = mem.mint_plan_id();
        let c = mem.mint_plan_id();
        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(a, c);
    }

    #[test]
    fn insert_and_lookup_by_id() {
        let mut mem = PlanMemory::default();
        let plan = held_plan(
            1,
            PlanState::Background,
            PlanSource::Brain(BrainType::Rational),
            0.2,
        );
        mem.insert(plan);
        assert!(mem.get(PlanId(1)).is_some());
        assert!(mem.get(PlanId(999)).is_none());
    }

    #[test]
    fn count_state_filters_correctly() {
        let mut mem = PlanMemory::default();
        mem.insert(held_plan(
            1,
            PlanState::Background,
            PlanSource::Brain(BrainType::Rational),
            0.1,
        ));
        mem.insert(held_plan(
            2,
            PlanState::Executing,
            PlanSource::Brain(BrainType::Rational),
            1.0,
        ));
        mem.insert(held_plan(
            3,
            PlanState::Background,
            PlanSource::Brain(BrainType::Rational),
            0.5,
        ));
        assert_eq!(mem.count_state(PlanState::Background), 2);
        assert_eq!(mem.count_state(PlanState::Executing), 1);
        assert_eq!(mem.count_state(PlanState::Considering), 0);
    }

    #[test]
    fn evict_excess_drops_lowest_commitment_background_first() {
        let mut mem = PlanMemory::default();
        mem.insert(held_plan(
            1,
            PlanState::Background,
            PlanSource::Brain(BrainType::Rational),
            0.1,
        ));
        mem.insert(held_plan(
            2,
            PlanState::Background,
            PlanSource::Brain(BrainType::Rational),
            0.8,
        ));
        mem.insert(held_plan(
            3,
            PlanState::Executing,
            PlanSource::Brain(BrainType::Rational),
            1.0,
        ));

        let evicted = mem.evict_excess(2);
        assert_eq!(evicted, vec![PlanId(1)]);
        assert!(mem.get(PlanId(1)).is_none());
        assert!(mem.get(PlanId(2)).is_some());
        assert!(
            mem.get(PlanId(3)).is_some(),
            "Executing plans must never be evicted by the cognitive-load cap"
        );
    }

    #[test]
    fn evict_protects_verbal_commitments_over_self_generated() {
        let mut mem = PlanMemory::default();
        mem.insert(held_plan(
            1,
            PlanState::Background,
            PlanSource::VerbalCommitment {
                promised_to: Entity::from_bits(1),
                agreement_tick: 0,
            },
            0.1,
        ));
        mem.insert(held_plan(
            2,
            PlanState::Background,
            PlanSource::Brain(BrainType::Rational),
            0.9,
        ));

        let evicted = mem.evict_excess(1);
        // Self-generated drops first even though its commitment is higher.
        assert_eq!(evicted, vec![PlanId(2)]);
        assert!(
            mem.get(PlanId(1)).is_some(),
            "verbal commitment must survive eviction when a self-generated plan is available"
        );
    }

    #[test]
    fn evict_falls_back_to_verbal_when_no_other_candidates() {
        let mut mem = PlanMemory::default();
        mem.insert(held_plan(
            1,
            PlanState::Background,
            PlanSource::VerbalCommitment {
                promised_to: Entity::from_bits(1),
                agreement_tick: 0,
            },
            0.1,
        ));
        mem.insert(held_plan(
            2,
            PlanState::Background,
            PlanSource::VerbalCommitment {
                promised_to: Entity::from_bits(2),
                agreement_tick: 0,
            },
            0.9,
        ));

        let evicted = mem.evict_excess(1);
        // Only verbal commitments exist — eviction picks the lowest.
        assert_eq!(evicted, vec![PlanId(1)]);
    }

    #[test]
    fn max_plans_for_scales_with_conscientiousness_and_openness() {
        let neutral = max_plans_for(0.5, 0.5, 0.5);
        let disciplined_curious = max_plans_for(1.0, 1.0, 0.0);
        let anxious = max_plans_for(0.0, 0.0, 1.0);

        assert!(disciplined_curious > neutral);
        assert!(anxious <= neutral);
        assert!(disciplined_curious > BASE_MAX_PLANS);
    }

    #[test]
    fn is_finished_when_cursor_past_end() {
        let plan = HeldPlan {
            current_step: 3,
            steps: Vec::new(),
            ..held_plan(
                1,
                PlanState::Executing,
                PlanSource::Brain(BrainType::Rational),
                1.0,
            )
        };
        assert!(plan.is_finished());
    }

    #[test]
    fn current_returns_none_when_finished() {
        let plan = HeldPlan {
            current_step: 3,
            steps: Vec::new(),
            ..held_plan(
                1,
                PlanState::Executing,
                PlanSource::Brain(BrainType::Rational),
                1.0,
            )
        };
        assert!(plan.current().is_none());
    }
}
