//! Generic engagement primitive: a persistent multi-tick interaction
//! between two or more agents that one plugin owns end-to-end.
//!
//! Conversation is the first kind. Hunt, Tend, Court, Nurse, etc. ship as
//! their own kinds against the same primitive.

use bevy::prelude::*;

/// Newtype for engagement handles. Generated by [`EngagementRegistry`]
/// at engagement start, stored on each participant's [`Engaged`]
/// component, and used to look up the kind-specific payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Reflect, serde::Serialize)]
pub struct EngagementId(pub u64);

/// What kind of engagement this is. The kind selects the inner-loop
/// systems and the conflict signature used by arbitration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Reflect, serde::Serialize)]
pub enum EngagementKind {
    Converse,
}

/// Component attached to agents currently inside an engagement.
///
/// Carries the kind (so consumers can branch on what the agent is doing)
/// and the handle (so plugins can fetch the kind-specific payload from
/// their own registry / manager). Replaces the old `InConversation`
/// marker — turn ownership and group membership live on the kind's
/// payload, not on this component.
#[derive(Component, Debug, Clone, Reflect)]
#[reflect(Component)]
pub struct Engaged {
    pub kind: EngagementKind,
    pub id: EngagementId,
}

impl Engaged {
    pub fn new(kind: EngagementKind, id: EngagementId) -> Self {
        Self { kind, id }
    }
}

/// Reasons an engagement ended, surfaced on the
/// [`SimEventKind::EngagementEnded`](crate::agent::events::SimEventKind::EngagementEnded)
/// event so consumers (relationship updates, decision-trace UI) can
/// react differently to a graceful farewell vs an abandonment vs an
/// emotion-driven break.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Reflect, serde::Serialize)]
pub enum EngagementEndReason {
    /// Natural close — last beat carried the kind's "wrap up" intent
    /// (Farewell, etc.). No relationship penalty.
    Natural,
    /// Inner loop went quiet for too long without a closing beat.
    Stale,
    /// One participant moved out of range and the others lost contact.
    OutOfRange,
    /// Acute fear/pain crossed the engagement-break threshold and
    /// arbitration admitted a non-engagement proposal that displaced
    /// the engagement's own action.
    EmotionOverride,
    /// One participant left without a closing beat. The remaining
    /// participants' relationship updaters apply the abandonment
    /// penalty.
    Abandoned,
    /// Some other plugin or invariant tore the engagement down.
    Other,
}
